channel_sources:
- conda-forge
channel_targets:
- cryoem main
c_compiler_version:
- '9'    # [osx]
- '7'    # [linux]
numpy:
  - 1.18
  - 1.19
pyt:
  - '3.7.* *_cpython'
  - '3.8.* *_cpython'
  - '3.9.* *_cpython'
