{% if openmpi == "3" %}
{% set branch = "py-path" %}
{% elif openmpi == "4" %}
{% set branch = "py3-ompi4" %}
{% endif %}

package:
    name: pydusa
    {% if openmpi == "3" %}
    version: 1.30
    {% elif openmpi == "4" %}
    version: 1.40
    {% endif %}

source:
    url: https://github.com/cryoem/pydusa/archive/{{ branch }}.tar.gz
    fn: pydusa-{{ branch }}.tar.gz

build:
    number: 0
    skip: True  # [win or py<37]

requirements:
    build:
        - {{ compiler('c') }}
    host:
        - python
        - numpy
        - openmpi {{ openmpi }}
        - fftw * mpi_openmpi_*
    run:
        {% for package in resolved_packages('host') %}
        - {{ package }}
        {% endfor %}

test:
  imports:
    - mpi

about:
  license: GPL-2.0
  summary: Pydusa is a package for parallel programming using Python.
