{% set version = "3.1" %}
{% set tag = "v" + version %}

package:
    name: pydusa
    version: {{ version }}

source:
    url: https://github.com/cryoem/pydusa/archive/{{ tag }}.tar.gz
    fn: pydusa-{{ tag }}.tar.gz

build:
    number: 1
    skip: True  # [win]

requirements:
    build:
        - {{ compiler('c') }}
        - make
        - sysroot_linux-64 2.17  # [linux64]
    host:
        - python
        - numpy
        - openmpi
        - fftw * mpi_openmpi_*
    run:
        - python
        - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x.x') }}
        - openmpi
        - fftw * mpi_openmpi_*

test:
  requires:
    - openssh

  files:
    - mpi_test.py
  imports:
    - mpi

  commands:
    - ompi_info
    - python -c "import mpi; print(mpi.pydusa_version())"
    - mpirun --oversubscribe -n 4 python mpi_test.py

about:
  license: GPL-2.0
  summary: Pydusa is a package for parallel programming using Python.
