{% set version = "3.0" %}
{% set tag = "v" + version %}

package:
    name: pydusa
    version: {{ version }}

source:
    url: https://github.com/cryoem/pydusa/archive/{{ tag }}.tar.gz
    fn: pydusa-{{ tag }}.tar.gz

build:
    number: 0
    skip: True  # [win or py<37]

requirements:
    build:
        - {{ compiler('c') }}
    host:
        - python
        - numpy
        - openmpi 3
        - fftw 3.3.8 mpi_openmpi_*
    run:
        {% for package in resolved_packages('host') %}
        - {{ package }}
        {% endfor %}

test:
  imports:
    - mpi

about:
  license: GPL-2.0
  summary: Pydusa is a package for parallel programming using Python.
