travis:
  secure:
    BINSTAR_TOKEN: NaVt4I3TRyOj8xR2vDpE+Q/U40qxqolyxTwa82p0tQykagA7qToNpexetP22SwWJF1PH0nzwIHwYryaiClBik+0tHs+dVuChlDyOuT/PW+Fms76HCBjW/De3yC+ZG83dCUK0VHX1nAiXTirRg962l2PLOqf73iRkAAn2c2gUg8fEHvj//kYHzRPEI997F5sln1SPbkVXrKuhnZ5KPmi0NTt7d8gChkcKbObC4VpWbdoGStGtvy32pm5ynI+iKnHsoUO41UW8E5PYkEH6QKs/u9gtpXGtOswqaSytSTCHCw7dWzSWsGYy4gUjnttN2k4hBWPEspbYqT+yKbETHUReyc15uAW/bvtDsShNKYTTejlJ9WUzgxsNLT5zth+Jp3R+KTYChElncUGgGwwb87/Zg1dwRfqrE0h3NIZFsuGTdwQVwW2eS7RD7VrQNUjk/Ic2L3SDzRjEgIz5XZ8m/4/LPNVKdq7fBYhpW8gn1CjYko7aHCaWtVHRDOMHQxZGD8xnX9SQsNM4MeT4eabYnB3566z8apdQ8/qb5tR8HX/JtCMSAAFncc+ya/mDJS4Xg/D15jlKdCXzdbNPC3dqgbaSz9KXp3ET3jlhuUXaLLcWPTWs2u0PsH9bp9fGAQFfJRj6bgd27D1ev8Yud3N2eb6bL3NFqkXicahshIY8L96ouxk=

channels:
  sources: [cryoem, defaults, conda-forge]
  targets:
  - [cryoem, main]

github:
  user_or_org: cryoem
  repo_name: pydusa-feedstock

provider:
  linux: circle
  osx: travis

azure:
  build_id: blank

channel_priority: flexible
