channels:
  targets:
  - [cryoem, main]

github:
  user_or_org: cryoem
  repo_name: pydusa-feedstock

provider:
  linux: github_actions
  osx: github_actions

os_version:
  linux_64: cos7

build_platform:
  osx_arm64: osx_64
test_on_native_only: true
