channels:
  targets:
  - [cryoem, main]

github:
  user_or_org: cryoem
  repo_name: pydusa-feedstock

provider:
  linux: circle
  osx: github_actions

azure:
  build_id: blank

channel_priority: flexible
