channels:
  sources: [cryoem, defaults, conda-forge]
  targets:
  - [cryoem, main]

github:
  user_or_org: cryoem
  repo_name: pydusa-feedstock

provider:
  linux: circle
  osx: travis

azure:
  build_id: blank

channel_priority: flexible
